---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    - host: nginx.s<номер своего логина>.edu.slurm.io
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  number: 80
